name: Build and push dotnet API to container registry

on:
  workflow_call:
    inputs:
      DOTNET-VERSION:
        required: true
        type: string        
      CONTAINER-NAME:
        required: true
        type: string
      CONTAINER-REGISTRY:
        required: true
        type: string
      APPLICATION-FOLDER:
        required: true
        type: string
    outputs:
      tag:
        description: "Full build tag for built container image"
        value: ${{ jobs.build.outputs.tag }}
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Source
        
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ inputs.DOTNET-VERSION }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -p:PublishDir=out
      
    - name: 'Login to container registry'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ inputs.CONTAINER-REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
      # Want to do: docker build -f Dockerfile.k8s . -t ${{ tag }}
      
    - name: 'Build and push'
      id: tag
      run: |
       cd ./${{ inputs.APPLICATION-FOLDER }}
       echo "::set-output name=tag::$INPUTS_CONTAINER-REGISTRY/$INPUTS_CONTAINER-NAME:$GITHUB_SHA"
       env
       docker build -f Dockerfile.k8s . -t ${{ inputs.CONTAINER-REGISTRY }}/${{ inputs.CONTAINER-NAME }}:${{ github.sha }}
       docker push ${{ inputs.CONTAINER-REGISTRY }}/${{ inputs.CONTAINER-NAME }}:${{ github.sha }}
